"""
Static fashion inventory used across all tasks.
"""
from fashion_env.models import ClothingItem

INVENTORY: list[ClothingItem] = [
    # --- TOPS ---
    ClothingItem(id="T001", name="White Oxford Shirt", category="top", color="white",
                 style_tags=["formal", "classic", "office"], season=["spring", "fall", "winter"],
                 price=59.99, brand="Brooks Brothers", size_available=["XS","S","M","L","XL"]),
    ClothingItem(id="T002", name="Black Turtleneck", category="top", color="black",
                 style_tags=["classic", "minimalist", "office"], season=["fall", "winter"],
                 price=44.99, brand="COS", size_available=["XS","S","M","L"]),
    ClothingItem(id="T003", name="Floral Wrap Blouse", category="top", color="multicolor",
                 style_tags=["boho", "casual", "feminine"], season=["spring", "summer"],
                 price=38.99, brand="Zara", size_available=["S","M","L","XL"]),
    ClothingItem(id="T004", name="Striped Breton Top", category="top", color="navy",
                 style_tags=["casual", "classic", "nautical"], season=["spring", "summer"],
                 price=29.99, brand="Saint James", size_available=["XS","S","M","L","XL"]),
    ClothingItem(id="T005", name="Sequin Cami Top", category="top", color="gold",
                 style_tags=["party", "glamorous", "evening"], season=["fall", "winter"],
                 price=55.00, brand="ASOS", size_available=["XS","S","M","L"]),
    ClothingItem(id="T006", name="Linen Crop Top", category="top", color="beige",
                 style_tags=["casual", "boho", "resort"], season=["summer"],
                 price=25.99, brand="H&M", size_available=["XS","S","M","L","XL"]),
    ClothingItem(id="T007", name="Blazer (Fitted)", category="top", color="navy",
                 style_tags=["formal", "office", "classic"], season=["spring", "fall", "winter"],
                 price=129.99, brand="Banana Republic", size_available=["XS","S","M","L","XL"]),
    ClothingItem(id="T008", name="Graphic Band Tee", category="top", color="black",
                 style_tags=["casual", "edgy", "streetwear"], season=["spring", "summer", "fall"],
                 price=19.99, brand="Urban Outfitters", size_available=["XS","S","M","L","XL","XXL"]),

    # --- BOTTOMS ---
    ClothingItem(id="B001", name="Tailored Trousers", category="bottom", color="charcoal",
                 style_tags=["formal", "office", "classic"], season=["spring", "fall", "winter"],
                 price=89.99, brand="Theory", size_available=["XS","S","M","L","XL"]),
    ClothingItem(id="B002", name="High-Waist Mom Jeans", category="bottom", color="light blue",
                 style_tags=["casual", "retro", "classic"], season=["spring", "summer", "fall"],
                 price=65.00, brand="Levi's", size_available=["24","26","28","30","32","34"]),
    ClothingItem(id="B003", name="Flowy Midi Skirt", category="bottom", color="dusty rose",
                 style_tags=["feminine", "boho", "casual"], season=["spring", "summer"],
                 price=49.99, brand="Free People", size_available=["XS","S","M","L"]),
    ClothingItem(id="B004", name="Pleated Mini Skirt", category="bottom", color="plaid",
                 style_tags=["preppy", "casual", "retro"], season=["fall", "winter"],
                 price=42.00, brand="Mango", size_available=["XS","S","M","L","XL"]),
    ClothingItem(id="B005", name="Wide-Leg Linen Pants", category="bottom", color="cream",
                 style_tags=["resort", "boho", "casual"], season=["summer"],
                 price=55.00, brand="Vince", size_available=["XS","S","M","L","XL"]),
    ClothingItem(id="B006", name="Black Skinny Jeans", category="bottom", color="black",
                 style_tags=["casual", "edgy", "classic"], season=["fall", "winter", "spring"],
                 price=69.99, brand="AG Jeans", size_available=["24","26","28","30","32"]),
    ClothingItem(id="B007", name="Satin Slip Skirt", category="bottom", color="champagne",
                 style_tags=["party", "glamorous", "evening"], season=["fall", "winter"],
                 price=75.00, brand="Reformation", size_available=["XS","S","M","L"]),

    # --- SHOES ---
    ClothingItem(id="S001", name="White Leather Sneakers", category="shoes", color="white",
                 style_tags=["casual", "minimalist", "classic"], season=["spring", "summer", "fall"],
                 price=110.00, brand="Common Projects", size_available=["36","37","38","39","40","41"]),
    ClothingItem(id="S002", name="Black Pointed Heels", category="shoes", color="black",
                 style_tags=["formal", "office", "evening", "classic"], season=["spring", "fall", "winter"],
                 price=145.00, brand="Steve Madden", size_available=["35","36","37","38","39","40"]),
    ClothingItem(id="S003", name="Strappy Sandals", category="shoes", color="tan",
                 style_tags=["casual", "boho", "resort", "summer"], season=["summer", "spring"],
                 price=75.00, brand="Sam Edelman", size_available=["35","36","37","38","39","40","41"]),
    ClothingItem(id="S004", name="Block Heel Mules", category="shoes", color="camel",
                 style_tags=["office", "classic", "transitional"], season=["spring", "fall"],
                 price=99.00, brand="Aldo", size_available=["35","36","37","38","39","40"]),
    ClothingItem(id="S005", name="Platform Combat Boots", category="shoes", color="black",
                 style_tags=["edgy", "streetwear", "casual"], season=["fall", "winter"],
                 price=155.00, brand="Dr. Martens", size_available=["36","37","38","39","40","41"]),
    ClothingItem(id="S006", name="Nude Ballet Flats", category="shoes", color="nude",
                 style_tags=["classic", "feminine", "office", "casual"], season=["spring", "summer", "fall"],
                 price=85.00, brand="Repetto", size_available=["35","36","37","38","39","40"]),
    ClothingItem(id="S007", name="Silver Strappy Heels", category="shoes", color="silver",
                 style_tags=["party", "glamorous", "evening"], season=["summer", "fall", "winter"],
                 price=120.00, brand="Zara", size_available=["35","36","37","38","39","40"]),

    # --- ACCESSORIES ---
    ClothingItem(id="A001", name="Silk Square Scarf", category="accessory", color="multicolor",
                 style_tags=["classic", "feminine", "chic"], season=["spring", "summer", "fall"],
                 price=45.00, brand="Hermès-inspired", size_available=["one size"]),
    ClothingItem(id="A002", name="Leather Belt", category="accessory", color="brown",
                 style_tags=["classic", "casual", "office"], season=["spring", "summer", "fall", "winter"],
                 price=35.00, brand="J.Crew", size_available=["XS","S","M","L","XL"]),
    ClothingItem(id="A003", name="Statement Gold Necklace", category="accessory", color="gold",
                 style_tags=["glamorous", "party", "evening", "boho"], season=["spring", "summer", "fall", "winter"],
                 price=55.00, brand="Madewell", size_available=["one size"]),
    ClothingItem(id="A004", name="Structured Tote Bag", category="accessory", color="tan",
                 style_tags=["office", "classic", "practical"], season=["spring", "summer", "fall", "winter"],
                 price=175.00, brand="Cuyana", size_available=["one size"]),
    ClothingItem(id="A005", name="Mini Crossbody Bag", category="accessory", color="black",
                 style_tags=["casual", "evening", "minimalist"], season=["spring", "summer", "fall", "winter"],
                 price=95.00, brand="Coach", size_available=["one size"]),
    ClothingItem(id="A006", name="Pearl Stud Earrings", category="accessory", color="white",
                 style_tags=["classic", "formal", "feminine", "office"], season=["spring", "summer", "fall", "winter"],
                 price=30.00, brand="Mikimoto-inspired", size_available=["one size"]),
    ClothingItem(id="A007", name="Oversized Sunglasses", category="accessory", color="tortoise",
                 style_tags=["casual", "boho", "glamorous"], season=["spring", "summer"],
                 price=65.00, brand="Ray-Ban", size_available=["one size"]),
    ClothingItem(id="A008", name="Beaded Anklet", category="accessory", color="multicolor",
                 style_tags=["boho", "resort", "casual", "summer"], season=["summer"],
                 price=18.00, brand="Anthropologie", size_available=["one size"]),

    # --- OUTERWEAR ---
    ClothingItem(id="O001", name="Classic Trench Coat", category="outerwear", color="camel",
                 style_tags=["classic", "office", "formal", "transitional"], season=["spring", "fall"],
                 price=320.00, brand="Burberry-inspired", size_available=["XS","S","M","L","XL"]),
    ClothingItem(id="O002", name="Oversized Denim Jacket", category="outerwear", color="medium wash",
                 style_tags=["casual", "retro", "streetwear"], season=["spring", "summer", "fall"],
                 price=89.99, brand="Levi's", size_available=["XS","S","M","L","XL","XXL"]),
    ClothingItem(id="O003", name="Faux Fur Teddy Coat", category="outerwear", color="ivory",
                 style_tags=["cozy", "glamorous", "casual"], season=["winter", "fall"],
                 price=199.00, brand="ASOS", size_available=["XS","S","M","L","XL"]),
    ClothingItem(id="O004", name="Leather Moto Jacket", category="outerwear", color="black",
                 style_tags=["edgy", "casual", "streetwear"], season=["spring", "fall", "winter"],
                 price=265.00, brand="AllSaints", size_available=["XS","S","M","L","XL"]),
]

INVENTORY_BY_ID: dict = {item.id: item for item in INVENTORY}

# ── Extended inventory — 15 more items ───────────────────────────────────────
INVENTORY += [
    # TOPS
    ClothingItem(id="T009", name="Silk Blouse", category="top", color="ivory",
                 style_tags=["formal", "feminine", "classic", "office"], season=["spring", "fall", "winter"],
                 price=89.99, brand="Equipment", size_available=["XS","S","M","L","XL"]),
    ClothingItem(id="T010", name="Oversized Hoodie", category="top", color="grey",
                 style_tags=["casual", "streetwear", "cozy"], season=["fall", "winter"],
                 price=55.00, brand="Champion", size_available=["XS","S","M","L","XL","XXL"]),
    ClothingItem(id="T011", name="Halter Neck Top", category="top", color="red",
                 style_tags=["party", "feminine", "evening"], season=["summer", "spring"],
                 price=42.00, brand="Reformation", size_available=["XS","S","M","L"]),

    # BOTTOMS
    ClothingItem(id="B008", name="Leather Mini Skirt", category="bottom", color="black",
                 style_tags=["edgy", "party", "evening"], season=["fall", "winter"],
                 price=95.00, brand="AllSaints", size_available=["XS","S","M","L"]),
    ClothingItem(id="B009", name="Linen Wide Trousers", category="bottom", color="white",
                 style_tags=["resort", "casual", "minimalist"], season=["summer"],
                 price=72.00, brand="Arket", size_available=["XS","S","M","L","XL"]),

    # SHOES
    ClothingItem(id="S008", name="Kitten Heel Mules", category="shoes", color="nude",
                 style_tags=["feminine", "office", "classic"], season=["spring", "summer", "fall"],
                 price=135.00, brand="Mango", size_available=["35","36","37","38","39","40"]),
    ClothingItem(id="S009", name="White Knee High Boots", category="shoes", color="white",
                 style_tags=["edgy", "party", "retro"], season=["fall", "winter"],
                 price=189.00, brand="Steve Madden", size_available=["36","37","38","39","40"]),

    # ACCESSORIES
    ClothingItem(id="A009", name="Bucket Hat", category="accessory", color="beige",
                 style_tags=["casual", "resort", "streetwear"], season=["spring", "summer"],
                 price=28.00, brand="Lack of Color", size_available=["one size"]),
    ClothingItem(id="A010", name="Chain Belt", category="accessory", color="gold",
                 style_tags=["party", "edgy", "glamorous"], season=["spring", "summer", "fall", "winter"],
                 price=45.00, brand="ASOS", size_available=["XS","S","M","L","XL"]),
    ClothingItem(id="A011", name="Velvet Headband", category="accessory", color="black",
                 style_tags=["preppy", "feminine", "classic"], season=["fall", "winter"],
                 price=22.00, brand="Jennifer Behr", size_available=["one size"]),
    ClothingItem(id="A012", name="Woven Straw Bag", category="accessory", color="tan",
                 style_tags=["boho", "resort", "casual", "summer"], season=["spring", "summer"],
                 price=55.00, brand="Cult Gaia", size_available=["one size"]),

    # OUTERWEAR
    ClothingItem(id="O005", name="Longline Wool Coat", category="outerwear", color="camel",
                 style_tags=["classic", "formal", "office"], season=["fall", "winter"],
                 price=345.00, brand="Max Mara inspired", size_available=["XS","S","M","L","XL"]),
    ClothingItem(id="O006", name="Cropped Puffer Jacket", category="outerwear", color="pink",
                 style_tags=["casual", "streetwear", "cozy"], season=["winter", "fall"],
                 price=155.00, brand="Zara", size_available=["XS","S","M","L","XL"]),
    ClothingItem(id="O007", name="Sheer Kimono Wrap", category="outerwear", color="multicolor",
                 style_tags=["boho", "resort", "feminine"], season=["spring", "summer"],
                 price=68.00, brand="Free People", size_available=["XS","S","M","L","XL"]),
    ClothingItem(id="O008", name="Blazer (Oversized)", category="outerwear", color="black",
                 style_tags=["office", "classic", "edgy", "streetwear"], season=["spring", "fall", "winter"],
                 price=149.00, brand="H&M", size_available=["XS","S","M","L","XL","XXL"]),
]

INVENTORY_BY_ID = {item.id: item for item in INVENTORY}
